version: '3'

services:
  recommender_api:
    image: recommender-api-dev
    build:
      context: .
      dockerfile: Dockerfile_dev
    ports: 
    - "5000:5000"
    links:
      - redis
  redis:
    image: redis
